// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebOperateLog.proto

package com.ice.brother.house.common.proto;

public final class OperateLog {
  private OperateLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebOperateLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebOperateLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>string user = 2;</code>
     */
    java.lang.String getUser();
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <pre>
     *客户端ip地址.
     * </pre>
     *
     * <code>string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <pre>
     *客户端ip地址.
     * </pre>
     *
     * <code>string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *客户端真实Ip地址.
     * </pre>
     *
     * <code>string realIp = 4;</code>
     */
    java.lang.String getRealIp();
    /**
     * <pre>
     *客户端真实Ip地址.
     * </pre>
     *
     * <code>string realIp = 4;</code>
     */
    com.google.protobuf.ByteString
        getRealIpBytes();

    /**
     * <pre>
     *模块.
     * </pre>
     *
     * <code>string module = 5;</code>
     */
    java.lang.String getModule();
    /**
     * <pre>
     *模块.
     * </pre>
     *
     * <code>string module = 5;</code>
     */
    com.google.protobuf.ByteString
        getModuleBytes();

    /**
     * <pre>
     *请求路径.
     * </pre>
     *
     * <code>string requestUrl = 6;</code>
     */
    java.lang.String getRequestUrl();
    /**
     * <pre>
     *请求路径.
     * </pre>
     *
     * <code>string requestUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getRequestUrlBytes();

    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    int getParamsCount();
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    boolean containsParams(
        java.lang.String key);
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getParams();
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getParamsMap();
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    java.lang.String getParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    java.lang.String getParamsOrThrow(
        java.lang.String key);

    /**
     * <pre>
     *请求方式.
     * </pre>
     *
     * <code>string requestMethod = 8;</code>
     */
    java.lang.String getRequestMethod();
    /**
     * <pre>
     *请求方式.
     * </pre>
     *
     * <code>string requestMethod = 8;</code>
     */
    com.google.protobuf.ByteString
        getRequestMethodBytes();

    /**
     * <pre>
     *响应.
     * </pre>
     *
     * <code>string response = 9;</code>
     */
    java.lang.String getResponse();
    /**
     * <pre>
     *响应.
     * </pre>
     *
     * <code>string response = 9;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <pre>
     *耗时.
     * </pre>
     *
     * <code>uint64 duration = 10;</code>
     */
    long getDuration();

    /**
     * <pre>
     *日志生成时间.
     * </pre>
     *
     * <code>uint64 time = 11;</code>
     */
    long getTime();
  }
  /**
   * <pre>
   *message是固定的
   * </pre>
   *
   * Protobuf type {@code WebOperateLog}
   */
  public  static final class WebOperateLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WebOperateLog)
      WebOperateLogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebOperateLog.newBuilder() to construct.
    private WebOperateLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebOperateLog() {
      id_ = "";
      user_ = "";
      ip_ = "";
      realIp_ = "";
      module_ = "";
      requestUrl_ = "";
      requestMethod_ = "";
      response_ = "";
      duration_ = 0L;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WebOperateLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              realIp_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              module_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              requestUrl_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                params_ = com.google.protobuf.MapField.newMapField(
                    ParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              params__ = input.readMessage(
                  ParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              params_.getMutableMap().put(
                  params__.getKey(), params__.getValue());
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              requestMethod_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
            case 80: {

              duration_ = input.readUInt64();
              break;
            }
            case 88: {

              time_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OperateLog.internal_static_WebOperateLog_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OperateLog.internal_static_WebOperateLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OperateLog.WebOperateLog.class, OperateLog.WebOperateLog.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private volatile java.lang.Object user_;
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>string user = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名.
     * </pre>
     *
     * <code>string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <pre>
     *客户端ip地址.
     * </pre>
     *
     * <code>string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端ip地址.
     * </pre>
     *
     * <code>string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REALIP_FIELD_NUMBER = 4;
    private volatile java.lang.Object realIp_;
    /**
     * <pre>
     *客户端真实Ip地址.
     * </pre>
     *
     * <code>string realIp = 4;</code>
     */
    public java.lang.String getRealIp() {
      java.lang.Object ref = realIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realIp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户端真实Ip地址.
     * </pre>
     *
     * <code>string realIp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRealIpBytes() {
      java.lang.Object ref = realIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULE_FIELD_NUMBER = 5;
    private volatile java.lang.Object module_;
    /**
     * <pre>
     *模块.
     * </pre>
     *
     * <code>string module = 5;</code>
     */
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        module_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *模块.
     * </pre>
     *
     * <code>string module = 5;</code>
     */
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTURL_FIELD_NUMBER = 6;
    private volatile java.lang.Object requestUrl_;
    /**
     * <pre>
     *请求路径.
     * </pre>
     *
     * <code>string requestUrl = 6;</code>
     */
    public java.lang.String getRequestUrl() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求路径.
     * </pre>
     *
     * <code>string requestUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUrlBytes() {
      java.lang.Object ref = requestUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 7;
    private static final class ParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  OperateLog.internal_static_WebOperateLog_ParamsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> params_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetParams() {
      if (params_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      return params_;
    }

    public int getParamsCount() {
      return internalGetParams().getMap().size();
    }
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public boolean containsParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParams() {
      return getParamsMap();
    }
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
      return internalGetParams().getMap();
    }
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public java.lang.String getParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *请求参数.
     * </pre>
     *
     * <code>map&lt;string, string&gt; params = 7;</code>
     */

    public java.lang.String getParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int REQUESTMETHOD_FIELD_NUMBER = 8;
    private volatile java.lang.Object requestMethod_;
    /**
     * <pre>
     *请求方式.
     * </pre>
     *
     * <code>string requestMethod = 8;</code>
     */
    public java.lang.String getRequestMethod() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMethod_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求方式.
     * </pre>
     *
     * <code>string requestMethod = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMethodBytes() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_FIELD_NUMBER = 9;
    private volatile java.lang.Object response_;
    /**
     * <pre>
     *响应.
     * </pre>
     *
     * <code>string response = 9;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *响应.
     * </pre>
     *
     * <code>string response = 9;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 10;
    private long duration_;
    /**
     * <pre>
     *耗时.
     * </pre>
     *
     * <code>uint64 duration = 10;</code>
     */
    public long getDuration() {
      return duration_;
    }

    public static final int TIME_FIELD_NUMBER = 11;
    private long time_;
    /**
     * <pre>
     *日志生成时间.
     * </pre>
     *
     * <code>uint64 time = 11;</code>
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (!getRealIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, realIp_);
      }
      if (!getModuleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, module_);
      }
      if (!getRequestUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestUrl_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetParams(),
          ParamsDefaultEntryHolder.defaultEntry,
          7);
      if (!getRequestMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, requestMethod_);
      }
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, response_);
      }
      if (duration_ != 0L) {
        output.writeUInt64(10, duration_);
      }
      if (time_ != 0L) {
        output.writeUInt64(11, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (!getRealIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, realIp_);
      }
      if (!getModuleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, module_);
      }
      if (!getRequestUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestUrl_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        params__ = ParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, params__);
      }
      if (!getRequestMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, requestMethod_);
      }
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, response_);
      }
      if (duration_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, duration_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OperateLog.WebOperateLog)) {
        return super.equals(obj);
      }
      OperateLog.WebOperateLog other = (OperateLog.WebOperateLog) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getUser()
          .equals(other.getUser());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getRealIp()
          .equals(other.getRealIp());
      result = result && getModule()
          .equals(other.getModule());
      result = result && getRequestUrl()
          .equals(other.getRequestUrl());
      result = result && internalGetParams().equals(
          other.internalGetParams());
      result = result && getRequestMethod()
          .equals(other.getRequestMethod());
      result = result && getResponse()
          .equals(other.getResponse());
      result = result && (getDuration()
          == other.getDuration());
      result = result && (getTime()
          == other.getTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + REALIP_FIELD_NUMBER;
      hash = (53 * hash) + getRealIp().hashCode();
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule().hashCode();
      hash = (37 * hash) + REQUESTURL_FIELD_NUMBER;
      hash = (53 * hash) + getRequestUrl().hashCode();
      if (!internalGetParams().getMap().isEmpty()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParams().hashCode();
      }
      hash = (37 * hash) + REQUESTMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMethod().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDuration());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OperateLog.WebOperateLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OperateLog.WebOperateLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OperateLog.WebOperateLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OperateLog.WebOperateLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OperateLog.WebOperateLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OperateLog.WebOperateLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OperateLog.WebOperateLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OperateLog.WebOperateLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OperateLog.WebOperateLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OperateLog.WebOperateLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OperateLog.WebOperateLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OperateLog.WebOperateLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OperateLog.WebOperateLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *message是固定的
     * </pre>
     *
     * Protobuf type {@code WebOperateLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WebOperateLog)
        OperateLog.WebOperateLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OperateLog.internal_static_WebOperateLog_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OperateLog.internal_static_WebOperateLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OperateLog.WebOperateLog.class, OperateLog.WebOperateLog.Builder.class);
      }

      // Construct using com.ice.brother.house.common.proto.OperateLog.WebOperateLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        user_ = "";

        ip_ = "";

        realIp_ = "";

        module_ = "";

        requestUrl_ = "";

        internalGetMutableParams().clear();
        requestMethod_ = "";

        response_ = "";

        duration_ = 0L;

        time_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OperateLog.internal_static_WebOperateLog_descriptor;
      }

      @java.lang.Override
      public OperateLog.WebOperateLog getDefaultInstanceForType() {
        return OperateLog.WebOperateLog.getDefaultInstance();
      }

      @java.lang.Override
      public OperateLog.WebOperateLog build() {
        OperateLog.WebOperateLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OperateLog.WebOperateLog buildPartial() {
        OperateLog.WebOperateLog result = new OperateLog.WebOperateLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.user_ = user_;
        result.ip_ = ip_;
        result.realIp_ = realIp_;
        result.module_ = module_;
        result.requestUrl_ = requestUrl_;
        result.params_ = internalGetParams();
        result.params_.makeImmutable();
        result.requestMethod_ = requestMethod_;
        result.response_ = response_;
        result.duration_ = duration_;
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OperateLog.WebOperateLog) {
          return mergeFrom((OperateLog.WebOperateLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OperateLog.WebOperateLog other) {
        if (other == OperateLog.WebOperateLog.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getRealIp().isEmpty()) {
          realIp_ = other.realIp_;
          onChanged();
        }
        if (!other.getModule().isEmpty()) {
          module_ = other.module_;
          onChanged();
        }
        if (!other.getRequestUrl().isEmpty()) {
          requestUrl_ = other.requestUrl_;
          onChanged();
        }
        internalGetMutableParams().mergeFrom(
            other.internalGetParams());
        if (!other.getRequestMethod().isEmpty()) {
          requestMethod_ = other.requestMethod_;
          onChanged();
        }
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        if (other.getDuration() != 0L) {
          setDuration(other.getDuration());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OperateLog.WebOperateLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OperateLog.WebOperateLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>string user = 2;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>string user = 2;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>string user = 2;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名.
       * </pre>
       *
       * <code>string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <pre>
       *客户端ip地址.
       * </pre>
       *
       * <code>string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端ip地址.
       * </pre>
       *
       * <code>string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端ip地址.
       * </pre>
       *
       * <code>string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ip地址.
       * </pre>
       *
       * <code>string ip = 3;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ip地址.
       * </pre>
       *
       * <code>string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realIp_ = "";
      /**
       * <pre>
       *客户端真实Ip地址.
       * </pre>
       *
       * <code>string realIp = 4;</code>
       */
      public java.lang.String getRealIp() {
        java.lang.Object ref = realIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          realIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *客户端真实Ip地址.
       * </pre>
       *
       * <code>string realIp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRealIpBytes() {
        java.lang.Object ref = realIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户端真实Ip地址.
       * </pre>
       *
       * <code>string realIp = 4;</code>
       */
      public Builder setRealIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        realIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端真实Ip地址.
       * </pre>
       *
       * <code>string realIp = 4;</code>
       */
      public Builder clearRealIp() {
        
        realIp_ = getDefaultInstance().getRealIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端真实Ip地址.
       * </pre>
       *
       * <code>string realIp = 4;</code>
       */
      public Builder setRealIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        realIp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object module_ = "";
      /**
       * <pre>
       *模块.
       * </pre>
       *
       * <code>string module = 5;</code>
       */
      public java.lang.String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          module_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *模块.
       * </pre>
       *
       * <code>string module = 5;</code>
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        java.lang.Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *模块.
       * </pre>
       *
       * <code>string module = 5;</code>
       */
      public Builder setModule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块.
       * </pre>
       *
       * <code>string module = 5;</code>
       */
      public Builder clearModule() {
        
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *模块.
       * </pre>
       *
       * <code>string module = 5;</code>
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        module_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestUrl_ = "";
      /**
       * <pre>
       *请求路径.
       * </pre>
       *
       * <code>string requestUrl = 6;</code>
       */
      public java.lang.String getRequestUrl() {
        java.lang.Object ref = requestUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求路径.
       * </pre>
       *
       * <code>string requestUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getRequestUrlBytes() {
        java.lang.Object ref = requestUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求路径.
       * </pre>
       *
       * <code>string requestUrl = 6;</code>
       */
      public Builder setRequestUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求路径.
       * </pre>
       *
       * <code>string requestUrl = 6;</code>
       */
      public Builder clearRequestUrl() {
        
        requestUrl_ = getDefaultInstance().getRequestUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求路径.
       * </pre>
       *
       * <code>string requestUrl = 6;</code>
       */
      public Builder setRequestUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestUrl_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> params_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetParams() {
        if (params_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        return params_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableParams() {
        onChanged();;
        if (params_ == null) {
          params_ = com.google.protobuf.MapField.newMapField(
              ParamsDefaultEntryHolder.defaultEntry);
        }
        if (!params_.isMutable()) {
          params_ = params_.copy();
        }
        return params_;
      }

      public int getParamsCount() {
        return internalGetParams().getMap().size();
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public boolean containsParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getParams() {
        return getParamsMap();
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
        return internalGetParams().getMap();
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public java.lang.String getParamsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public java.lang.String getParamsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetParams().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParams() {
        internalGetMutableParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public Builder removeParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableParams() {
        return internalGetMutableParams().getMutableMap();
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */
      public Builder putParams(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *请求参数.
       * </pre>
       *
       * <code>map&lt;string, string&gt; params = 7;</code>
       */

      public Builder putAllParams(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableParams().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object requestMethod_ = "";
      /**
       * <pre>
       *请求方式.
       * </pre>
       *
       * <code>string requestMethod = 8;</code>
       */
      public java.lang.String getRequestMethod() {
        java.lang.Object ref = requestMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求方式.
       * </pre>
       *
       * <code>string requestMethod = 8;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMethodBytes() {
        java.lang.Object ref = requestMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求方式.
       * </pre>
       *
       * <code>string requestMethod = 8;</code>
       */
      public Builder setRequestMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求方式.
       * </pre>
       *
       * <code>string requestMethod = 8;</code>
       */
      public Builder clearRequestMethod() {
        
        requestMethod_ = getDefaultInstance().getRequestMethod();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求方式.
       * </pre>
       *
       * <code>string requestMethod = 8;</code>
       */
      public Builder setRequestMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <pre>
       *响应.
       * </pre>
       *
       * <code>string response = 9;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *响应.
       * </pre>
       *
       * <code>string response = 9;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *响应.
       * </pre>
       *
       * <code>string response = 9;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应.
       * </pre>
       *
       * <code>string response = 9;</code>
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应.
       * </pre>
       *
       * <code>string response = 9;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        response_ = value;
        onChanged();
        return this;
      }

      private long duration_ ;
      /**
       * <pre>
       *耗时.
       * </pre>
       *
       * <code>uint64 duration = 10;</code>
       */
      public long getDuration() {
        return duration_;
      }
      /**
       * <pre>
       *耗时.
       * </pre>
       *
       * <code>uint64 duration = 10;</code>
       */
      public Builder setDuration(long value) {
        
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *耗时.
       * </pre>
       *
       * <code>uint64 duration = 10;</code>
       */
      public Builder clearDuration() {
        
        duration_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *日志生成时间.
       * </pre>
       *
       * <code>uint64 time = 11;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *日志生成时间.
       * </pre>
       *
       * <code>uint64 time = 11;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *日志生成时间.
       * </pre>
       *
       * <code>uint64 time = 11;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WebOperateLog)
    }

    // @@protoc_insertion_point(class_scope:WebOperateLog)
    private static final OperateLog.WebOperateLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OperateLog.WebOperateLog();
    }

    public static OperateLog.WebOperateLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebOperateLog>
        PARSER = new com.google.protobuf.AbstractParser<WebOperateLog>() {
      @java.lang.Override
      public WebOperateLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebOperateLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebOperateLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebOperateLog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OperateLog.WebOperateLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebOperateLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebOperateLog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebOperateLog_ParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebOperateLog_ParamsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WebOperateLog.proto\"\215\002\n\rWebOperateLog\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004user\030\002 \001(\t\022\n\n\002ip\030\003 \001(\t\022\016\n" +
      "\006realIp\030\004 \001(\t\022\016\n\006module\030\005 \001(\t\022\022\n\nrequest" +
      "Url\030\006 \001(\t\022*\n\006params\030\007 \003(\0132\032.WebOperateLo" +
      "g.ParamsEntry\022\025\n\rrequestMethod\030\010 \001(\t\022\020\n\010" +
      "response\030\t \001(\t\022\020\n\010duration\030\n \001(\004\022\014\n\004time" +
      "\030\013 \001(\004\032-\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001B0\n\"com.ice.brother.house.c" +
      "ommon.ptotoB\nOperateLogb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WebOperateLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WebOperateLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebOperateLog_descriptor,
        new java.lang.String[] { "Id", "User", "Ip", "RealIp", "Module", "RequestUrl", "Params", "RequestMethod", "Response", "Duration", "Time", });
    internal_static_WebOperateLog_ParamsEntry_descriptor =
      internal_static_WebOperateLog_descriptor.getNestedTypes().get(0);
    internal_static_WebOperateLog_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebOperateLog_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
