server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: house-advert-web
feign:
  hystrix:
    enabled: true

  profiles:
    active: dev

