
logging:
  path: classpath:log-dev.xml


# kafka
bootstrap:
  servers: 127.0.0.1:9092
enable:
  auto:
    commit: true
auto:
  commit:
    interval:
      ms: 1000
key:
  deserializer: org.apache.kafka.common.serialization.StringDeserializer
value:
  deserializer: org.apache.kafka.common.serialization.StringDeserializer

#kafka log group,topic
kafka:
  log:
    group: testGroup
    topic: my-topic
