server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: house-app-web

  profiles:
    active: dev

log:
  topic: WEB_OPERATE_LOG

tworker:
  quartz: 1000
thread:
  size: 2
